[theme]
base = "light"
primaryColor = "#012D1D"
backgroundColor = "#FDF9F0"
secondaryBackgroundColor = "#FAF7F2"
textColor = "#1C1C16"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"
